'use client';

import { useRef, useState } from 'react';
import { Braces, Code2, Github, Layers3, Menu, X, Linkedin, Mail, Plus, Terminal, Check, Globe2 } from 'lucide-react';
import { profile, projects } from '@/data/portfolio';

function ProjectPreview({ kind }: { kind: string }) {
  if (kind === 'orbit') return <div className="mock orbit" aria-hidden="true"><div className="mock-side"><b>◈ orbit</b><span className="selected">▦ Vue d’ensemble</span><span>▤ Mes projets</span><span>◷ Activité</span><span>⚙ Paramètres</span><small>WORKSPACE PERSONNEL</small></div><div className="mock-main"><div className="mock-top">Mon espace <span>◉</span></div><h4>Let’s make it happen.</h4><p>Un petit pas, un grand projet.</p><div className="stat-row"><div>Projets en cours<strong>08 <small>+2 ce mois</small></strong></div><div>Tâches terminées<strong>24 <small>+12 cette semaine</small></strong></div></div><div className="mock-list"><span>Projets récents</span>{['Portfolio personnel', 'Application mobile', 'Design system'].map((p, i) => <div key={p}><i style={{ background: ['#b5a5ef', '#e8b693', '#9ccbb5'][i] }} />{p}<b>{['En cours', 'En cours', 'Terminé'][i]}</b></div>)}</div></div></div>;
  if (kind === 'forma') return <div className="mock forma" aria-hidden="true"><div className="shop-nav"><b>forma.</b><span>Collection &nbsp; Notre histoire</span><span>Panier (0)</span></div><div className="shop-heading"><small>LE DESIGN AU QUOTIDIEN</small><h4>Moins, mais mieux.</h4><p>Une sélection d’objets essentiels.</p></div><div className="swatches"><div><span className="swatch swatch-one">01<br/><b>Épure</b></span><p>Collection Épure <b>Découvrir</b></p></div><div><span className="swatch swatch-two">02<br/><b>Matière</b></span><p>Collection Matière <b>Découvrir</b></p></div><div><span className="swatch swatch-three">03<br/><b>Essentiel</b></span><p>Collection Essentiel <b>Découvrir</b></p></div></div></div>;
  return <div className="mock pulse" aria-hidden="true"><div className="pulse-nav"><b>ϟ pulse</b><span>Overview &nbsp; Services &nbsp; Logs</span><small>Demo workspace</small></div><div className="pulse-title"><h4>Tout est sous contrôle.</h4><span><i /> All systems operational</span></div><div className="pulse-stats"><div>Uptime<strong>99.98<small>%</small></strong></div><div>Temps de réponse<strong>124<small>ms</small></strong></div><div>Services actifs<strong>12<small>/12</small></strong></div></div><div className="chart"><div className="chart-label">Temps de réponse <span>24 dernières heures</span></div><div className="bars">{[30, 45, 36, 50, 34, 42, 38, 60, 45, 39, 48, 58, 40, 47, 60, 80, 55, 48, 58, 47, 50, 44, 65, 51, 48, 63, 56, 42, 52, 48, 62, 51].map((h, i) => <i key={i} style={{ height: `${h}%` }} />)}</div><div className="chart-axis"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span></div></div></div>;
}

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeProject, setActiveProject] = useState(projects[0]);
  const dialog = useRef<HTMLDialogElement>(null);
  const nav = [{ href: '#projets', text: 'Projets' }, { href: '#apropos', text: 'À propos' }, { href: '#competences', text: 'Compétences' }];
  return <>
    <a className="skip-link" href="#main">Aller au contenu</a>
    <header className="site-header"><div className="container header-inner"><a href="#" className="logo" aria-label="Noam, accueil">noam<span>.</span><span className="logo-slash">/</span><span className="logo-dev">dev</span></a><nav aria-label="Navigation principale" className="desktop-nav">{nav.map(n => <a key={n.href} href={n.href}>{n.text}</a>)}</nav><a href="#contact" className="header-contact">Parlons de votre projet <span>✳</span></a><button className="mobile-toggle" aria-label={menuOpen ? 'Fermer le menu' : 'Ouvrir le menu'} aria-expanded={menuOpen} aria-controls="mobile-nav" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <nav id="mobile-nav" className="mobile-nav" aria-label="Navigation mobile">{[...nav, { href: '#contact', text: 'Contact' }].map(n => <a key={n.href} href={n.href} onClick={() => setMenuOpen(false)}>{n.text}</a>)}</nav>}</header>
    <main id="main">
      <section className="hero container" aria-labelledby="hero-title"><div className="hero-eyebrow"><span className="tiny-code">&lt;/&gt;</span> DÉVELOPPEUR WEB <span className="eyebrow-line" /> DES IDÉES AU PIXEL</div><div className="hero-main"><div><h1 id="hero-title">Je code des idées.<br/>Je crée des <span className="accent">expériences<span className="title-dot">.</span></span></h1><p className="hero-description">Moi, c’est {profile.name}. J’aime transformer des idées en interfaces<br className="desktop-break"/> soignées, intuitives et agréables à utiliser.</p><div className="hero-actions"><a className="button button-primary" href="#projets">Explorer mes projets <Layers3 size={17} /></a><a className="text-link" href="#apropos">Un peu plus sur moi <Plus size={17} /></a></div></div><div className="code-note"><div className="code-note-top"><span /><span /><span /><small>hello.ts</small></div><code><span className="code-muted">// Toujours en construction</span><br/><span className="code-purple">const</span> developer = {'{'}<br/>&nbsp; name: <span className="code-green">'{profile.name}'</span>,<br/>&nbsp; fuel: <span className="code-green">'curiosité'</span>,<br/>&nbsp; focus: <span className="code-green">'le prochain détail'</span><br/>{'}'};<br/><br/><span className="code-purple">while</span> (learning) {'{'}<br/>&nbsp; <span className="code-green">build</span>();<br/>{'}'}<span className="cursor" /></code><div className="code-note-bottom"><span>TypeScript</span><span>UTF-8</span></div></div></div><div className="hero-footer"><span>DE L’INTENTION À L’INTERACTION.</span><span>DESIGN SENSIBLE. CODE SOLIDE.</span><span className="scroll-hint">SCROLL POUR EXPLORER <span>↓</span></span></div></section>
      <div className="tech-strip"><div className="container tech-inner">{['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Node.js', 'Git'].map((t, i) => <span key={t}><span className="tech-symbol">{['N', '⚛', 'TS', '≈', '⬡', '◇'][i]}</span>{t}</span>)}</div></div>
      <section id="projets" className="container section projects-section"><div className="section-kicker"><span>01 / PROJETS</span><span>DE L’IDÉE À L’ÉCRAN</span></div><div className="section-heading"><h2>Le code prend <span>forme.</span></h2><p>Trois concepts pour explorer ce que l’on peut créer.<br/>Projets de démonstration à remplacer par mes réalisations.</p></div><div className="project-grid">{projects.map((project, index) => <article key={project.id} className={`project-card ${index === 0 ? 'project-featured' : ''}`}><button className={`project-preview ${project.color}`} onClick={() => { setActiveProject(project); dialog.current?.showModal(); }} aria-label={`Découvrir le concept ${project.name}`}><div className="preview-label"><span>CONCEPT {project.number}</span><span>{project.category}</span></div><ProjectPreview kind={project.id} /><span className="preview-open"><Plus size={20}/></span></button><div className="project-info"><div><span className="project-category">{project.category}</span><button className="project-title" onClick={() => { setActiveProject(project); dialog.current?.showModal(); }}>{project.name}<Plus size={22}/></button><p>{project.description}</p></div><div className="tags">{project.tags.map(t => <span key={t}>{t}</span>)}</div></div></article>)}</div></section>
      <section id="apropos" className="about-section"><div className="container about-grid"><div><div className="section-kicker">02 / À PROPOS</div><h2>Curieux par nature.<br/><span>Développeur par passion.</span></h2></div><div className="about-copy"><p>Ce qui me plaît dans le développement ? Partir d’une page blanche et construire quelque chose que l’on a envie d’utiliser.</p><p>Je m’intéresse autant à ce qui se voit qu’à ce qui se passe derrière : une interface claire, une interaction fluide et du code que l’on peut faire évoluer.</p><div className="about-note"><Terminal size={18}/><span>Apprendre. Construire. Recommencer.</span></div></div></div></section>
      <section id="competences" className="container section"><div className="section-kicker">03 / BOÎTE À OUTILS</div><div className="section-heading"><h2>Les bons outils.<br/><span>Les bonnes idées.</span></h2><p>Un aperçu des technologies de ce portfolio.<br/>Une base pour construire, tester et aller plus loin.</p></div><div className="skills-grid">{[{ icon: Code2, title: 'Interfaces & expérience', text: 'Des pages pensées pour tous les écrans, avec une attention portée aux détails.', tags: ['React', 'Next.js', 'HTML / CSS'] }, { icon: Braces, title: 'Logique & structure', text: 'Des composants réutilisables et un code organisé pour faire évoluer les idées.', tags: ['TypeScript', 'JavaScript', 'Composants'] }, { icon: Terminal, title: 'Du code au web', text: 'Un projet versionné et prêt à être construit puis mis en ligne.', tags: ['Git', 'npm', 'Vercel'] }].map(s => <article className="skill-card" key={s.title}><s.icon size={25}/><h3>{s.title}</h3><p>{s.text}</p><div className="tags">{s.tags.map(t => <span key={t}>{t}</span>)}</div></article>)}</div></section>
      <section id="contact" className="container contact-section"><div className="contact-top"><span className="section-kicker">04 / ET MAINTENANT ?</span><span className="contact-star" aria-hidden="true">✳</span></div><h2>Une idée en tête ?<br/><span>Créons la suite.</span></h2><div className="contact-bottom"><p>Un projet, une collaboration ou simplement envie d’échanger.<br/>Les belles choses commencent par une conversation.</p>{profile.email ? <a className="button button-primary" href={`mailto:${profile.email}`}>Discutons ensemble <Mail size={18}/></a> : <span className="contact-pending"><Mail size={18}/> Coordonnées bientôt disponibles</span>}</div><div className="social-links">{profile.github && <a href={profile.github} target="_blank" rel="noreferrer"><Github size={17}/>GitHub</a>}{profile.linkedin && <a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin size={17}/>LinkedIn</a>}</div></section>
    </main><footer className="container footer"><a className="logo" href="#">noam<span>.</span></a><span>© {new Date().getFullYear()} Noam · Fait avec soin, et du code.</span><a href="#">Retour en haut ↑</a></footer>
    <dialog ref={dialog} className="project-dialog" onClick={e => { if (e.target === e.currentTarget) dialog.current?.close(); }} aria-labelledby="dialog-title"><div className="dialog-inner"><button className="dialog-close" onClick={() => dialog.current?.close()} aria-label="Fermer le détail du projet" autoFocus><X/></button><span className="section-kicker">PROJET DE DÉMONSTRATION / {activeProject.number}</span><h2 id="dialog-title">{activeProject.name}<span>.</span></h2><div className={`dialog-preview ${activeProject.color}`}><ProjectPreview kind={activeProject.id}/></div><p>{activeProject.details}</p><div className="tags">{activeProject.tags.map(t => <span key={t}><Check size={13}/>{t}</span>)}</div><div className="dialog-links">{activeProject.github && <a className="button button-secondary" href={activeProject.github} target="_blank" rel="noreferrer"><Github size={17}/>Code source</a>}{activeProject.demo && <a className="button button-primary" href={activeProject.demo} target="_blank" rel="noreferrer"><Globe2 size={17}/>Voir le site</a>}</div></div></dialog>
  </>;
}
